name: deploy
on:
  push:
    branches: [main]
concurrency:
  group: deploy-main
  cancel-in-progress: false
permissions:
  contents: read
  pull-requests: read
  actions: read
jobs:
  deploy:
    uses: ship-iac/shipmate/.github/workflows/deploy.yml@1c7688d2465f6ed349fe8e5c2bd8f69ff55bbf12
    permissions: { contents: read, checks: read, pull-requests: read, actions: read }
    secrets: inherit
    with:
      state_suffix: terraform.tfstate.d
